### PR TITLE
Static Assets Option 1 (Bundle every asset and fingerprint w/ esbuild, replace references in outgoing responses)

### PR DESCRIPTION
**Pull request by ryanbethel**
This prototype adds background fingerprinting and rerefrencing of static assets. Users put static assets in the /public folder and reference them with a /_public path in the frontend. 

*This is still a prototype to get the behavior that we want. There are some places it could be optimized.*

This prototype followed a proposal I made in another channel:
> Here is my proposal for fixing the static file serving for Enhance users.
We setup a new magic route like _public so we don’t mess with the behavior of _static.
> - Bundle all static assets in the public folder into a lambda that responds to /_public
> - When deployed it gets hydrated with the map of fingerprinted names (similar to static.json but that is an implementation detail users never see).
> - It responds to any request for /_public/foo.jpg with a 200 but with “don’t cache” headers. It could 302 and point to the fingerprinted name, but this would add an extra request.
It responds to any request for the fingerprinted name /_public/foo-123xyz.jpg with a cache forever response.
>
>There are 3 ways that static files are requested:
> 1. Regular references from users code (i.e. href=/_public/foo.jpg): These references are regex replaced when deployed with the fingerprinted version of href=/_public/foo-123abc.jpg
> 2. Dynamically generate references in user code (i.e. href=${imageFile}): These can’t reliably be replace. They can use a helper like arc.static(imageFile). Or if they they will fallback to the uncached request to /_public/foo.jpg.
> 3. Circular references inside /public (i.e. if /_public/foo.js has an import for /_public/bar.js : These can’t be replaced because the fingerprint changes. But the _public lambda can do the search and replace when they are served so that when it is run on the client the downstream requests are fingerprinted.
>
> This means that users only ever reference /_public/<filename> or even /public/<filename> and they get the optimally cached versions unless they are dynamically generating the url. In that case it will still respond with a non-caching header. Or if they want to optimize it they have to learn about the enhance.public() helper (same behavior as arc.static).
>
>Update: After thinking about this it is probably not necessary to modify users node code at deploy. We can get away with running a search and replace in the enhance plugin before response is served.

### CODE REVIEW

**Comment by ryanbethel** [comment]
This PR also fixes a bug that caused the sandbox is run from somewhere other than the root directory. This is used in tests where we call sandbox.start({cwd:mockDir}).

**Review by tbeseda — COMMENTED** [review]
This all looks good to me. Mirrors how the new version of `@bundles` Arc plugin works with esbuild.
This definitely makes static assets references in Enhance easier.
I'll reserve final approval for our upcoming meeting on this 😄

**Comment by brianleroux** [comment]
> 1. Route name for assets: `/_public/<asset>` or `/public/<asset>` or something else

my vote is `/_public`

> 2. Do we attempt to bundle the assets in the public folder?

not sure if I understand how this is working to properly answer!

> 3. Should the bundling be done in the plugin-bundles?

Possibly not sure

> 4. Some of the discussion around changing this was to eliminate the static.json manifest file. This approach still uses a manifest file to replace the fingerprinted names before responses are sent. If it is important to eliminate a manifest, how can we do that?

No thats out of scope for now; just hiding it is good enough for userland

**Comment by ryanbethel** [comment]
One additional use case for static files is if a module needs to be used both on the backend in an api as well as on the client side. In that case the `plugin bundles` can be used to bundle the module by specifying it with the @bundles in the arc file.

**Pull request closed without merging**
