### PR TITLE
Add support for components folder

### PR DESCRIPTION
**Pull request by macdonst**

### CODE REVIEW

**Review by ryanbethel — APPROVED** [review]
This looks good. I really like the components folder. This makes it really nice to work with.

**Comment by colepeters** [comment]
What differentiates `components` from `elements`?

**Comment by macdonst** [comment]
@colepeters `elements` are pure sever side functions. `components` are client-side web components that export a `render` function which can be executed on the server as part of the initial SSR pass by Enhance.

**Comment by colepeters** [comment]
@macdonst Ahh interesting, thanks! Not sure if this is the time to discuss, but wondering if `components` is going to throw folks off as a name. I feel like a lot of folks will look at the name of that directory and presume it's where they should put the files that should actually go in `elements`? Wondering if there's a more purpose fit name that could work here, something less synonym-y to `elements`…? Maybe better to discuss F2F but wanted to throw that in for consideration ;)

**Comment by colepeters** [comment]
Gotcha, thanks! 'Components' has just become such a generic word that I worry about what associations/expectations people will bring to it. Naming, as always, is hard 😅

**Comment by kristoferjoseph** [comment]
@colepeters as @macdonst stated I am trying to anticipate DSD being generally available and I want to make sure we have an escape hatch for people wanting to write everything in JS even though it will have degraded performance without needing to hobble the way we handle elements or browser. We could name the folder something else but I as long as we document it we can name it whatever we want. I think components will be what people expect for where to place Web Components.

**Review by kristoferjoseph — APPROVED** [review]

**Pull request merged**
